[zap]
title = "ZAP Imóveis - busca salva"
# url = "https://www.zapimoveis.com.br/aluguel/apartamentos/sc+florianopolis++pantanal/?transacao=aluguel&onde=%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CPantanal%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3EPantanal%2C-27.614619%2C-48.516222%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CSaco+dos+Lim%C3%B5es%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3ESaco+dos+Limoes%2C-27.605591%2C-48.531228%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CCarvoeira%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3ECarvoeira%2C-27.594124%2C-48.526226%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CTrindade%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3ETrindade%2C-27.594124%2C-48.526226%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CC%C3%B3rrego+Grande%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3ECorrego+Grande%2C-27.591888%2C-48.493989%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CJos%C3%A9+Mendes%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3EJose+Mendes%2C-27.43122%2C-48.436261%2C&tipos=apartamento_residencial%2Ckitnet_residencial&pagina=1&precoTotalMaximo=2000&ordem=Mais+recente"
url = "https://www.zapimoveis.com.br/aluguel/apartamentos/sc+florianopolis++pantanal/?__ab=exp-aa-test%3Acontrol%2Cnovopos%3Anew%2Csuper-high%3Anew%2Colx%3Acontrol%2Cscore-rkg%3Acontrol%2Cphone-page%3Anew%2Cseo-texts%3Anew&transacao=aluguel&onde=%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CPantanal%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3EPantanal%2C-27.614619%2C-48.516222%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CSaco+dos+Lim%C3%B5es%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3ESaco+dos+Limoes%2C-27.605591%2C-48.531228%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CCarvoeira%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3ECarvoeira%2C-27.594124%2C-48.526226%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CTrindade%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3ETrindade%2C-27.594124%2C-48.526226%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CC%C3%B3rrego+Grande%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3ECorrego+Grande%2C-27.591888%2C-48.493989%2C%3B%2CSanta+Catarina%2CFlorian%C3%B3polis%2C%2CJos%C3%A9+Mendes%2C%2C%2Cneighborhood%2CBR%3ESanta+Catarina%3ENULL%3EFlorianopolis%3EBarrios%3EJose+Mendes%2C-27.43122%2C-48.436261%2C&tipos=apartamento_residencial%2Cstudio_residencial%2Ckitnet_residencial%2Ccasa_residencial&pagina=1&quartos=2%2C3%2C4&precoTotalMaximo=4000&ordem=Mais+recente"
entrySelector = "div.result-card"
titleSelector = "div.listing-price"
linkSelector = "div.result-card a"
contentSelector = "div.result-card div.l-card__content"

[imoveis-sc]
title = "Imóveis-SC"
url = "https://www.imoveis-sc.com.br/florianopolis/apartamento/caeira-do-saco-dos-limoes_carvoeira_corrego-grande_jose-mendes_pantanal_saco-dos-limoes_trindade/quartos/2,3?ordenacao=recentes&valor=-4000&area=30-"
entrySelector = "article.imovel"
titleSelector = "h2.imovel-titulo"
linkSelector = "h2.imovel-titulo a"
contentSelector = "article.imovel"

[chaves]
title = "Chaves na mão"
url = "https://www.chavesnamao.com.br/apartamentos-para-alugar/sc-florianopolis/saco-dos-limoes/2-quartos/?filtro=%7B%22bai%22%3A%5B13966%2C53003%2C13939%2C13952%2C13948%5D%2C%22pmax%22%3A4000%2C%22cnd%22%3Atrue%2C%22amin%22%3A30%7D"
entrySelector = "div[class^='imoveis__Card']"
titleSelector = "span.contentCard h2"
linkSelector = "span.contentCard a"
contentSelector = "div[class^='imoveis__Card']"

[ln-clips]
title = "Listen Notes - clips"
url = "https://www.listennotes.com/@aledts/podcast-clips/"
entrySelector = "[role='tabpanel'] > div > div"
titleSelector = "h3 > a"
linkSelector = "h3 > a"
contentSelector = ".ln-page-card > div > div:nth-child(2)"
dateSelector = "div time"
dateFormat = "MMM. dd, yyyy"

[dunker]
title = "Blog do Dunker | UOL"
url = "https://www.uol.com.br/tilt/colunas/blog-do-dunker/"
entrySelector = "div.thumbnails-wrapper"
titleSelector = "h3"
linkSelector = "a"
contentSelector = "a > div"
dateSelector = "time"
dateFormat = "MM/dd/yyyy"
